apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitrepo
spec:
  interval: 1m
  ref:
    branch: dev-team

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomization
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: gitrepo
  prune: true
