apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-a-prod

resources:
  - namespace.yaml
  - ../../base

labels:
- includeSelectors: true
  pairs:
    env: prod
    toolkit.fluxcd.io/tenant: dev-team

patches:
  - target:
      kind: GitRepository
    patch: |
      - op: add
        path: /spec/url
        value: "https://github.com/fluxcd/flux2-multi-tenancy"
  - target:
      kind: GitRepository
    patch: |
      - op: add
        path: /spec/secretRef        
        value: 
          name: "secret-basic-auth"
  - target:
      kind: Kustomization
    patch: |
      - op: add
        path: /spec/path
        value: ./production
      - op: add
        path: /spec/targetNamespace
        value: tenant-a-prod
      - op: replace
        path: /metadata/name
        value: tenant-a-prod
  - target:
      kind: RoleBinding
    patch: |
      - op: replace
        path: /subjects/0/name
        value: gotk:tenant-a-prod:reconciler