name: 🚀 Request New Tenant Environment
description: Provision a new isolated GitOps tenant environment.
labels: ["new-tenant"]
body:
  - type: input
    id: tenant_id
    attributes:
      label: Tenant ID
      placeholder: e.g., tenant-b
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - dev
        - staging
        - prod
    validations:
      required: false
  - type: input
    id: git_url
    attributes:
      label: Git Repository URL
    validations:
      required: false
  - type: input
    id: git_path
    attributes:
      label: Git Path
  - type: input
    id: gcp_sa
    attributes:
      label: GCP Service Account Email
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: false
