apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-a-prod

resources:
  - namespace.yaml
  - ../../base
  - namespace.yaml
  - ../../base
  - namespace.yaml

labels:
- includeSelectors: true
  pairs:
    env: prod
    toolkit.fluxcd.io/tenant: dev-team
