apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-a-dev

resources:
  - namespace.yaml
  - ../../base

labels:
- includeSelectors: true
  pairs:
    env: dev
    toolkit.fluxcd.io/tenant: dev-team

patches:
  # - target:
  #     kind: GitRepository
  #   patch: |
  #     - op: add
  #       path: /spec/url
  #       value: "https://github.com/fluxcd/flux2-multi-tenancy"
  #     - op: add
  #       path: /spec/secretRef
  #       value: 
  #         name: "secret-basic-auth"
  - target:
      kind: Kustomization
    patch: |
      - op: add
        path: /spec/path
        value: ./staging
      - op: add
        path: /spec/targetNamespace
        value: tenant-a-dev
      - op: replace
        path: /metadata/name
        value: tenant-a-dev
      - op: replace
        path: /spec/serviceAccountName
        value: tenant-a-sa-dev
  - target:
      kind: ServiceAccount
    patch: |
      - op: replace
        path: /metadata/name
        value: tenant-a-sa-dev
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: "your-gcp-sa@your-project.iam.gserviceaccount.com"
  - target:
      kind: RoleBinding
    patch: |
      - op: replace
        path: /subjects/0/name
        value: gotk:tenant-a-dev:reconciler
      - op: replace
        path: /subjects/1/name
        value: tenant-a-sa-dev
      