name: Provision Tenant
on:
  issues:
    types: [opened]

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'new-tenant')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse Issue Form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/new-tenant.yml
      
      - name: Use Parsed Data
        run: |
          echo "Tenant: ${{ steps.issue-parser.outputs.tenant_id }}"
          echo "Environments: ${{ steps.issue-parser.outputs.environments }}"
          echo "what-happened: ${{ steps.issue-parser.outputs.what-happened }}"
